[jobs.editor]
command = ["cargo", "run", "-p", "editor"]
env.RUSTFLAGS = "-A warnings"
need_stdout = true

[jobs.web]
command = ["cargo", "run", "-p", "runtime", "--target", "wasm32-unknown-emscripten"]
env.RUSTFLAGS = "-A warnings"
need_stdout = true

[jobs.test-nowarn]
command = ["cargo", "test", "--", "--nocapture","--show-output"]
env.RUSTFLAGS = "-A warnings"
need_stdout = true
background = false
ignored_lines = []

# Run without warnings for nicer devex
[jobs.run-nowarn]
command = ["cargo", "run","-p", "runtime","-q"]
env.RUSTFLAGS = "-A warnings"
need_stdout = true
background = false
ignored_lines = []

[jobs.build]
command = ["cargo", "build"]
