[workspace]
resolver = "3"
members = ["editor", "runtime"]

[profile.release]
# Extra 
lto = "fat"
strip = "symbols"
# Same as usual
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
