[workspace]
resolver = "3"
members = ["editor", "runtime"]

[profile.dev]
# Emscripten does not like -O2 + debug info
opt-level = 1
lto = "off"
debug = true
debug-assertions = true
overflow-checks = true

[profile.release]
# Extra 
lto = "fat"
strip = "symbols"
# Same as usual
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
