[target.x86_64-unknown-linux-musl]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y libmp3lame-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libsdl2-mixer-dev",
    "export PKG_CONFIG_SYSROOT_DIR=/",
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "DEBIAN_FRONTEND=noninteractive apt-get install -y libmp3lame-dev:$CROSS_DEB_ARCH libsdl2-dev:$CROSS_DEB_ARCH libsdl2-image-dev:$CROSS_DEB_ARCH libsdl2-ttf-dev:$CROSS_DEB_ARCH libsdl2-gfx-dev:$CROSS_DEB_ARCH libsdl2-mixer-dev:$CROSS_DEB_ARCH",
]
